### ISSUE TITLE
InnoDB error on "make up" (Windows 10)

### ISSUE THREAD

**Issue by ahmadmzak** [unee-t/bugzilla-customisation#55] opened 2018-04-09 01:18 UTC
`db_1        | 2018-04-09  1:12:02 140000618817408 [ERROR] InnoDB: The Auto-extending innodb_system data file './ibdata1' is of a different size 0 pages than specified in the .cnf file: initial 768 pages, max 0 (relevant if non-zero) pages!
db_1        | 2018-04-09  1:12:02 140000618817408 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
db_1        | 2018-04-09  1:12:02 140000618817408 [Note] InnoDB: Starting shutdown...
db_1        | 2018-04-09  1:12:03 140000618817408 [ERROR] Plugin 'InnoDB' init function returned error.
db_1        | 2018-04-09  1:12:03 140000618817408 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
db_1        | 2018-04-09  1:12:03 140000618817408 [Note] Plugin 'FEEDBACK' is disabled.
db_1        | 2018-04-09  1:12:03 140000618817408 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
db_1        | 2018-04-09  1:12:03 140000618817408 [ERROR] Unknown/unsupported storage engine: InnoDB
db_1        | 2018-04-09  1:12:03 140000618817408 [ERROR] Aborting
db_1        |
bugzillacustomisation_db_1 exited with code 1
`

I'm getting this error when trying to get bugzilla running on Windows 10. Any ideas on what might be causing this?

**Comment by kaihendry** [comment] 2018-04-09 01:31
Perhaps figure out how to run a mysql database service in Docker first on Windows? This is not a Bugzilla or Unee-T issue.

https://github.com/unee-t/bugzilla-customisation/blob/master/docker-compose.yml

Pro-tip for development: Don't use Windows.

**Comment by franck-boullier** [comment] 2018-04-09 11:01
@ahmadmzak the way I do it is to run an AWS EC2 instance just for that. 

@kaihendry can you post the video explainer link that you did sometime back: it should help a lot (and I can't find it anymore...)

**Comment by franck-boullier** [comment] 2018-04-11 01:06
@ahmadmzak this video should help you create your DEV environment
https://vimeo.com/264168929

**Comment by franck-boullier** [comment] 2018-04-27 20:44
closing this issue: Windows is not the preferred dev environment: too many compatibility issues with our LAMP stack.
It's best to create a dedicated AWS EC2 free tier machine to do the dev.
The video explains how to do that.

**Closed as completed by franck-boullier** 2018-04-27 20:44 UTC
